# Site settings
title: Coinomi
email: 
description: "Secure, lightweight, universal HD wallet for Bitcoin and other Crypto-Currencies"
baseurl: ""
url: https://coinomi.com
enforce_ssl: coinomi.com

# Build settings
markdown: redcarpet
permalink: pretty
